version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    container_name: mysql-bsn
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: virtual_bookshelf
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_USER: root
        MYSQL_PASSWORD: admin
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - spring-demo
  mail-dev:
      container_name: mail-dev-bsn
      image: maildev/maildev
      ports:
        - 1080:1080
        - 1025:1025

networks:
  spring-demo:
    driver: bridge

volumes:
  mysql-volume:
    driver: local